import Head from "next/head";
import Link from "next/link";
import { signOut, getSession } from "next-auth/react";
import { MongoClient, ObjectId } from "mongodb";

export async function getServerSideProps(context) {
  const session = await getSession(context)
  
  if (!session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }
  
  const pID = context.query.pid

  // CONNECT TO MONGODB DATABASE
  const client = await MongoClient.connect(process.env.MONGODB_URI);
  const db = client.db(process.env.MONGODB_DB);

  // QUERY FOR SPECIFIC DATA
  const profileData = await db.collection("profile").findOne({_id: new ObjectId(pID) });

  client.close();

  // SERIALIZE DATA AND TURN IT INTO JSON
  const serializedData = JSON.parse(JSON.stringify(profileData));

  // ADD TO PROPS OBJECT TO EXTRACT AS PROPS IN THE PAGE JSX
  return {
    props: {
      profileData: serializedData,
    }
  }

}

export default function View({ profileData}) {

  
    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <button onClick={() => signOut({callbackurl: "/"})}>Sign Out</button><br/>
        <Link href="/connections">Connections Page</Link> <br/>
        <Link href={`/profile/edit/${profileData._id}`}>Edit Page</Link> 


        <h2>View Profile Page of {profileData.sname}</h2>
        <h2>Identity</h2>
        <p>Super Name: {profileData.sname}</p>
        <p>Real Name: {profileData.rname}</p>
        <p>Age: {profileData.age}</p>
        <p>Location: {profileData.location}</p>
        <p>Species: {profileData.species}</p>
        <p>Gender: {profileData.gender}</p>
        <p>Sexual Orientation: {profileData.sex}</p>
        <h2>Attributes</h2>
        <p>Abilities: {profileData.ability}</p>
        <p>Side: {profileData.hva}</p>
        <p>Affiliation: {profileData.tpi}</p>
        <h2>Bio</h2>
        <p>Backstory: {profileData.story}</p>
      </main>
    </>
  )
}