import Head from "next/head";
import { signIn, signOut, getSession } from "next-auth/react";

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}

export default function Home({ session}) {

  if (session) {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <h2>Home Page</h2>
          <button onClick={() => signOut()}>Sign Out</button>
          <h3>Profile Info</h3>
          <p>Signed in as: {session.user.name}</p>
          <p>Email: {session.user.email}</p>
        </main>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <h2>Home Page</h2>
          <button onClick={() => signIn('google', {callbackUrl: '/connections'})}>Sign In</button>
        </main>
      </>
    );
  }
}
