import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Edit() {
  const router = useRouter()
  const {pid} = router.query
  
    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h2>Edit Profile Page of {pid}</h2>
      </main>
    </>
  )
}