import Head from "next/head";
import Link from "next/link";
import { motion } from "framer-motion";
import { getSession } from "next-auth/react";
import { MongoClient } from "mongodb";

export async function getServerSideProps(context) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  const pID = context.query.pid;
  const userEmail = session.user.email;

  // CONNECT TO MONGODB DATABASE
  const client = await MongoClient.connect(process.env.MONGODB_URI);
  const db = client.db(process.env.MONGODB_DB);

  // QUERY FOR SPECIFIC DATA
  const profileData = await db.collection("profile").findOne({ userEmail });

  client.close();

  // SERIALIZE DATA AND TURN IT INTO JSON
  const serializedData = JSON.parse(JSON.stringify(profileData));

  // ADD TO PROPS OBJECT TO EXTRACT AS PROPS IN THE PAGE JSX
  return {
    props: {
      profileData: serializedData,
      pID
    },
  };
}

export default function Edit({ profileData, pID }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header className="w-11/12 h-[8vh] mx-auto flex items-center justify-between">
        <Link href="/">
          <div className="flex items-center justify-between w-48">
            <img
              className="w-16"
              src="https://i.imgur.com/0BIn6HA.png"
              alt="Super Logo"
            />
          </div>
        </Link>
        <Link href={`/profile/view/${pID}`}>
          <motion.button
              whileHover={{scale: 1.1}}
              transition={{ type: "spring", stiffness: 400, damping: 10 }}
              className="w-48 p-2 rounded-lg font-semibold bg-[#4478ff] text-white text-xl mx-auto" type="submit">
                Cancel
              </motion.button>
        </Link>
        <section>
          <motion.button
            whileHover={{ scale: 1.2 }}
            transition={{ type: "spring", stiffness: 400, damping: 10 }}
            className="text-xl font-semibold border-2 border-[#4478ff] rounded-md px-2"
            onClick={() => signOut({ callbackUrl: "/" })}
          >
            Sign Out
          </motion.button>
        </section>
      </header>
      <main className="w-full h-[92vh] flex justify-center items-center bg-blue-200">
        <section className="w-[60rem] h-[90%] bg-white p-5 rounded-xl shadow-xl">
          <h2 className="text-2xl font-semibold">Edit Profile</h2>
          <form
            action="/api/update-action"
            method="POST"
            className="w-full h-full flex flex-col justify-evenly"
          >
            <section className="flex flex-col mx-auto">
              <label className="mb-[2px]">Super Name</label>
              <input
                className="w-56 border-solid border-2 border-black bg-blue-100 rounded-md text-lg px-2"
                type="text"
                name="sname"
                defaultValue={profileData.sname}
              />
            </section>
            <section className="flex justify-evenly">
              <section className="flex flex-col">
                <label className="mb-[2px]">Real Name</label>
                <input
                  className="w-56 border-solid border-2 border-black bg-blue-100 rounded-md text-lg px-2"
                  type="text"
                  name="rname"
                  defaultValue={profileData.rname}
                />
              </section>
              <section className="flex flex-col">
                <label className="mb-[2px]">Age</label>
                <input
                  className="w-56 border-solid border-2 border-black bg-blue-100 rounded-md text-lg px-2"
                  type="number"
                  min="0"
                  name="age"
                  defaultValue={profileData.age}
                />
              </section>
              <section className="flex flex-col">
                <label className="mb-[2px]">Location</label>
                <input
                  className="w-56 border-solid border-2 border-black bg-blue-100 rounded-md text-lg px-2"
                  type="text"
                  name="location"
                  defaultValue={profileData.location}
                />
              </section>
            </section>
            <section className="flex justify-evenly">
              <section className="flex flex-col">
                <label className="mb-[2px]">Species</label>
                <input
                  className="w-56 border-solid border-2 border-black bg-blue-100 rounded-md text-lg px-2"
                  type="text"
                  name="species"
                  defaultValue={profileData.species}
                />
              </section>
              <section className="flex flex-col">
                <label className="mb-[2px]">Gender (if human)</label>
                <select
                 className="w-56 border-solid border-2 border-black bg-blue-100 rounded-md text-lg px-2"
                  name="gender"
                  defaultValue={profileData.gender}
                >
                  <option value="" disabled hidden>
                    Gender
                  </option>
                  <option value="Agender">Agender</option>
                  <option value="Androgynous">Androgynous</option>
                  <option value="Bigender">Bigender</option>
                  <option value="Cisgender">Cisgender</option>
                  <option value="Cis Woman">Cis Woman</option>
                  <option value="Cis Man">Cis Man</option>
                  <option value="Non-binary">Non-binary</option>
                  <option value="Gender Fluid">Gender Fluid</option>
                  <option value="Gender Questioning">Gender Questioning</option>
                  <option value="Transgender">Transgender</option>
                  <option value="Trans Woman">Trans Woman</option>
                  <option value="Trans Man">Trans Man</option>
                  <option value="Transgender Person">Transgender Person</option>
                  <option value="Two-Spirit">Two-Spirit</option>
                </select>
              </section>
              <section className="flex flex-col">
                <label className="mb-[2px]">Sexual Orientation</label>
                <select
                  className="w-56 border-solid border-2 border-black bg-blue-100 rounded-md text-lg px-2"
                  name="sex"
                  defaultValue={profileData.sex}
                >
                  <option value="" disabled hidden>
                    Sexual Orientation
                  </option>
                  <option value="Asexual">Asexual</option>
                  <option value="Bisexual">Bisexual</option>
                  <option value="Gay">Gay</option>
                  <option value="Lesbian">Lesbian</option>
                  <option value="Pansexual">Pansexual</option>
                  <option value="Polysexual">Polysexual</option>
                  <option value="Queer">Queer</option>
                  <option value="Questioning">Questioning</option>
                  <option value="Straight">Straight</option>
                </select>
              </section>
            </section>
            

            <section className="flex flex-col mx-auto">
              <label className="mb-[2px]">Abilities</label>
              <input
                className="w-56 border-solid border-2 border-black bg-blue-100 rounded-md text-lg px-2"
                type="text"
                name="ability"
                defaultValue={profileData.ability}
              />
            </section>
            <section className="flex justify-evenly">
              <section className="flex flex-col">
                <label className="mb-[2px]">Side</label>
                <select
                  className="w-56 border-solid border-2 border-black bg-blue-100 rounded-md text-lg px-2"
                  name="hva"
                  defaultValue={profileData.hva}
                >
                  <option value="" disabled hidden>
                    Select your Side
                  </option>
                  <option value="Hero">Hero</option>
                  <option value="Villain">Villain</option>
                  <option value="Anti-Hero">Anti-Hero</option>
                </select>
              </section>
              <section className="flex flex-col">
                <label className="mb-[2px]">Affiliation</label>
                <select
                  className="w-56 border-solid border-2 border-black bg-blue-100 rounded-md text-lg px-2"
                  name="tpi"
                  defaultValue={profileData.tpi}
                >
                  <option value="" disabled hidden>
                    Team/Partner/Indie
                  </option>
                  <option value="I am on a team">I&#39;m on a team</option>
                  <option value="I have a partner">I have a partner</option>
                  <option value="I work independently">
                    I work independently
                  </option>
                </select>
              </section>
            </section>
            <section className="flex flex-col mx-auto">
              <label className="mb-[2px]">Backstory</label>
              <textarea
                className="w-96 border-solid border-2 border-black bg-blue-100 rounded-md text-lg px-2"
                name="story"
                rows="4"
                cols="50"
                maxLength="500"
                placeholder="Born with abilities beyond imagination, I grew up in a world that could not understand them..."
                defaultValue={profileData.story}
              />
            </section>
            <motion.button 
            whileHover={{scale: 1.1}} 
            transition={{ type: "spring", stiffness: 400, damping: 10 }}
            className="w-52 p-2 rounded-lg font-semibold bg-[#4478ff] text-white text-xl mx-auto" type="submit">
              Save
            </motion.button>
          </form>
        </section>
      </main>
    </>
  );
}
